# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:            '고광종'
tagline:          'GwangJong Ko'
description:      '설명을 써주세여'
url:              'https://koptimizer.github.io/forcha2.io/'
baseurl:          '/'

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
